name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.7, 3.8, 3.9]
    services:
      arangodb:
        image: arangodb/arangodb
        ports:
          - 8529/tcp
        env:
          ARANGO_ROOT_PASSWORD: password
    steps:
    - name: Setup Python ${{ matrix.python_version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r dev_requirements.txt
        python -m pip install numpy
    - name: flake8 src
      run: |
        flake8 src
    - name: flake8 tests
      run: |
        flake8 tests
    - name: flake8 examples
      run: |
        flake8 examples
    - name: Run tests..
      run: |
        coverage run -m unittest discover -s tests
        coverage combine
        coverage report --fail-under 70
      env:
        TEST_ARANGO_CLUSTER_URLS: http://127.0.0.1:${{ job.services.arangodb.ports['8529'] }}
        TEST_ARANGO_DB: test_arango_crud
        TEST_ARANGO_USERNAME: root
        TEST_ARANGO_PASSWORD: password
    - name: Run examples..
      run: |
        coverage run --rcfile=.coveragerc_examples examples/run_all.py
        coverage report --show-missing --fail-under 100
      env:
        ARANGO_CLUSTER: http://127.0.0.1:${{ job.services.arangodb.ports['8529'] }}
        ARANGO_DB: arango_crud
        ARANGO_AUTH: basic
        ARANGO_AUTH_USERNAME: root
        ARANGO_AUTH_PASSWORD: password
        ARANGO_APPLY_BASIC_CONFIG: true
        ARANGO_TTL_SECONDS: 3600
